### PR TITLE
Replace private with protected

### PR DESCRIPTION
**Pull request by angelogulina**
I would suggest to use `protected` instead of `private` to let the class be inheritable.
What do you think?

### CODE REVIEW

**Comment by widoz** [comment]
Hello @AngeloGulina and thanks for the pull request.

I usually worked with inheritance in mind in the past but for the kind of programming we do today I prefer **composition** over **inheritance** for a lot's of reasons.

The first one is **debuggability** followed by **testability**, **scalability** and **maintenability** (let me pass the terms).

**Inheritance** looks good at the first glance but more complex the project become much difficult is to **maintain** and **debug** code that use inheritance, because of the mantenability becomes hard, the **scalability** and **reusability** will suffers. Everything is connected (cit.)

When you have to deal with 3, 4 or more levels of inheritance, **debugging** the code become much difficult, because you go up and down to figure out how the inheritance for that specific implementation works for a code that probably you had written weeks ago and you completely forgot about it. 

Inheritance also means coupled code and coupled code is another way to say the code may produce more bugs that are difficult to find and fix.

Another thing is **testability**. 
When you make unit tests, you should test the code in isolation, that means you should test only the part you need without worry about other stuffs. No other functions, no other classes etc...

When you work with inheritance you cannot test in real isolation and also you have to take in mind that if the test fails you cannot be sure that the test fails because of the code you are testing or because of the inherited code (you cannot test abstract classes because them cannot be instantiate). So you must debug the test to know what is wrong (Time that you can use to do things instead of debug something that is supposed to help you and not create problems).

**Maintenability**. As we said, inheritance means coupled code that for his nature is difficult to maintain because all of the parts are strictly related to each others. Maintain a coupled code is more expensive than maintain a code that make use of **composition** and **dependency injection**, why? Because using inheritance you must maintain the code as an inscindible block, where using composition you can maintain the single parts separately.

In **Composition** the code parts are indipendents so, you can have a reusable code that is easy to **debug** because you focus only on the part you want without worry about and anything else.
Means that your code is more scalable because you can use the same code in different projects without bright down all of the dependecies. Famous is the quote 

> "You wanted a banana but what you got was a gorilla holding the banana and the entire jungle". 
cit. Joe Armstrong 

Have a look at the eric elliot article https://medium.com/javascript-scene/the-two-pillars-of-javascript-ee6f3281e7f3 that is a more authoritative source than me.

Composition is a better approch imho because you focus on create classes that do one thing and one thing only that you can reuse in different projects. Have a look at this article https://medium.com/humans-create-software/composition-over-inheritance-cb6f88070205 written by Mattias Petter Johansson for a better explanation.

Also, knowing about **Dependency Injection** could be more simple to think at composition to something more maintenable, scalable, testable and debuggable solution for your projects. Doesn't matter which size.

When you work using **composition** you work to create things, when you work using **inheritance** you work to create structures, to blow your mind into the hierarchy and optimization. 

A lot of times I spent my time on working using inheritance, creating 10 - 15 classes, interfaces, abstract classes to make a simple thing optimized thinking about how will be super efficient the code in the future if I'll would like to expand it. But the reality is that much of the time I created code that cannot be reused because it was high coupled, thinking on a refactoring that will never appear unless you are ready to go mad, because a week later you totally forgot about what was into your mind that time you wrote the code, and now you must start again, go up and down trying to figure out why your stupid self of the past wanted to make you mad.

This is why I don't develope using inheritance anymore but prefer to use **composition**, **dependency injection**, **inversion of control** and favoring the **code that depend on abstraction** raither than implementation. (See S.O.L.I.D)

Writing code using inheritance is a old school way that isn't more usefull these days.

**Comment by angelogulina** [comment]
Yo, @widoz, thanks for writing such a long reply 😅 everybody will benefit from it.

I know these principles and the specific articles as well (even if, to be honest, I don't quite grasp how could you use _this_ specific class in the _pr_ to be composed).

Anyway, close this one if you don't think it's useful.

---

Just want to describe my line of reasoning for clarity and given this is, as far as I understood, an Open Source project. In general you might have two options (probably more):

A) if you make the Class a final one, you get the "advantages" you described for yourself but people forking the repo will be forced to change the properties privacy in order to extend it;
B) if you make the Class suitable for extension, **you still get the advantages of your approach** but people will have the advantages of extension.

What I mean, in the end, is: just because something is possible, it **does not mean you have to do it**; but if you prohibit something right away, you are offering less possibilities.

Therefore, I would go for B), which I think would be a more inclusive and open choice.
Of course, my 2 cents 💰

---

Great work anyway 🤟🏻

**Comment by widoz** [comment]
> if you make the Class a final one, you get the "advantages" you described for yourself but people forking the repo will be forced to change the properties privacy in order to extend it;

The fact is, you don't need to extend it in any case, you can use a Decorator instead.

> In the Decorator pattern, a class will add functionality to another class, without changing the other classes' structure.

Cit. https://sourcemaking.com/design_patterns/decorator/php

>  I don't quite grasp how could you use this specific class in the pr to be composed

You can simply inject the object within another one that act as a Decorator.

Let's for example a project that use the Bem class, a project to handle templates but I want to camelize the strings.

```php
final class BemCamelCase implements Bem 
{
    private $bem;

    public function __construct(Bem $bem) {
         $this->bem = $bem;
    }

    public function scope() { 
        return toCamelCaseFunction($this->bem->scope());
    }

    public function block () { 
        return toCamelCaseFunction($this->bem->block());
    }

    public function element () {
       return toCamelCaseFunction($this->bem->element());
    }

    public function modifiers () {
       return toCamelCaseFunction($this->bem->modifiers());
    }
}
```

And the template class:

```php
class Template {

     private $bem;

     public function __constructor(Bem $bem) {
         $this->bem = $bem;
     } 

     public function data() {
         return (object)[
              'attributes' => [ 'class' => $this->bem->scope() ]
         ]
     }

     public function template(\stdClass $data) {
            // ... 
     }
}
```

To implement this I can simply:

```php
$bemUnprefixed = new BemCamelCase(new BemPrefixed());

$template = new Template($bemUnprefixed);
$template->template($template->data());
```

**Comment by widoz** [comment]
> B) if you make the Class suitable for extension, you still get the advantages of your approach but people will have the advantages of extension. 

Not sure, let's take an example:

**Example1.php**
```php
class BemPrefixed implements Bem, Prefix
{
  public function __construct($block, $element, $modifiers, $prefix = '') {}

  public function block() {}

  public function element() {}

  public function modifiers() {}

  public function prefix() {}
}

class BemUnprefixed extends BemPrefixed {

  public function __construct($block, $element, $modifiers) {}
}

$bemUnprefixed = new BemUnprefixed('block', 'element', ['modifiers']);

echo $bemUnprefixed->prefix(); // Ops, still accessible.
echo ($bemUnprefix instanceof Prefix); // true
```

Where 

**Example2.php**
```php
class BemUnprefixed implements Bem {
  public function __construct(Bem $bem) {}
  
  public function block() {}

  public function element() {}

  public function modifiers() {}
}

$bemUnprefixed = new BemUnprefixed(new BemPrefixed('block', 'element', ['modifiers']));

echo $bemUnprefixed->prefix(); // Fatal Error, the object doesn't have a `prefix` method.
echo ($bemUnprefix instanceof Prefix) // false
```

As you can see in **Example1.php** we have a problem, we can still access the method **prefix** even if the unprefixed version shouldn't have one. But that's ok, it's an implementation issue, but just an example.

A more correct way to implement it could be this one using inheritance:

```php
abstract class Bem
{
  public function __construct($block, $element, $modifiers);

  abstract public function block();

  abstract public function element();

  abstract public function modifiers();
}

class BemPrefix extends Bem {
  public function __construct($block, $element, $modifiers, $prefix) {
    parent::__construct($block, $element, $modifiers, $prefix);

    $this->prefix = $prefix;
  }

  public function prefix() {}
}

class BemCamelCase extends Bem {
  // Here I implements the camelCase code.
}

class BemCamelCasePrefixed extends BemPrefix {
  // Here I must implements again the camelCase code.
  // Also an `echo ($bemCamelCasePrefixed instanceof BemCamelCase)` will be false.
  // And we are talking about implementation not abstraction breaking the `D` of SOLID.
}

class Template {
  // I cannot pass a `BemCamelCasePrefixed` instance.
  public function __construct(BemCamelCase $bem) {}
}
```

But, this create a more complex structure, coupled and break the **Dependency Inversion Principle** https://en.wikipedia.org/wiki/Dependency_inversion_principle. 

I can create additional interfaces to fix the `D` issue but in this case I'll need to have:

```php
interface Bem {}
interface Prefix {}
interface CamelCase {}
interface BemCamelCase extends Bem, CamelCase {}
interface BemCamelCasePrefix extends Bem, CamelCase, Prefix {}

// Because you won't this to be implemented
abstract class BemAbstract implements Bem {}
class BemConcrete extends BemAbstract {}
class BemPrefix extends BemAbstract implements Prefix {}
class BemCamelCase extends BemAbstract implements CamelCase {}
// or should extend BemCamelCase and implements Prefix?
class BemCamelCasePrefixed extends BemPrefix, implements CamelCase {}
```

Now I can (with probably some problem) depend on abstraction. 
But the cost here is the **manutenibility**.

What instead something like:

```php
interface Bem {}
interface Prefix {}
interface CamelCase {}

class BemPrefixed implements Bem, Prefix {}
class BemCamelCase implements Bem, CamelCase {}
class BemCamelCasePrefixed implements Bem, Prefix, CamelCase {}

class Template {
  // Accept both: `BemCamelCase` and `BemCamelCasePrefixed`.
  public function __construct(BemCamelCase $bem) {}
}
```

In this latest case we allready fixed the `D` Principle, classes and interfaces are much cleaner and **manutenible**

I could used a more generic example but since we are talking about the implementation of BemPrefixed I preferred to base the code on it.

**Comment by angelogulina** [comment]
Many thanks a lot @widoz for the comprehensive reply.
I'm not sure we understood each other in the reasoning but I really appreciated all the examples.

As said, you can close this one if you find it not suitable 😄

**Pull request closed without merging**
